### ISSUE TITLE
 Import file 'generated/Gravity/Gravity.ts' not found?

### ISSUE THREAD

**Issue by yangmiok** [graphprotocol/example-subgraph#12]
```
⚠ Warnings loading subgraph from subgraph.yaml: Warnings in subgraph.yaml:
  
    Path: repository
    The repository is still set to https://github.com/graphprotocol/example-subgraph.
    Please replace it with a link to your subgraph source code.
  
    Path: description
    The description is still the one from the example subgraph.
    Please update it to tell users more about your subgraph.

✔ Load subgraph from subgraph.yaml
  Compile data source: Gravity => build/Gravity/Gravity.wasm
✖ Failed to compile subgraph: Failed to compile data source mapping: Import file 'generated/Gravity/Gravity.ts' not found.
Error: Failed to compile data source mapping: Import file 'generated/Gravity/Gravity.ts' not found.
    at Compiler._compileDataSourceMapping (/usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler.js:308:13)
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler.js:184:20
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1278:26)
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler.js:183:24
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3015:23)
➜  exa
```

**Comment by zhangtianai** [comment]
why?

**Comment by fafrd** [comment]
Did you forget to run `graph codegen`? or `npm run codegen` if you use it that way

**Comment by shashi278** [comment]
Any update on this?
I'm facing the same issue. I already ran `npm run codegen`. This issue comes while deploying.
This is my error:
```
$ npm run deploy

> What@0.1.0 deploy
> graph deploy shashi278/What --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/

Failed to compile subgraph Failed to compile subgraph: Error: Failed to compile data source mapping: Error: Import file 'generated/Gravity/Gravity.ts' not found.
```
