### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'Database does not use C locale.

### ISSUE THREAD

**Issue by utopiemaroc** [graphprotocol/example-subgraph#63]
hello,

when i try to Run example-subgraph with docker compose i have exited container error for "example-subgraph_graph-node_1" with this messages:

Jun 01 13:52:01.513 INFO Migrations finished, pool: main, shard: primary, component: ConnectionPool
thread 'tokio-runtime-worker' panicked at 'Database does not use C locale. Please check the graph-node documentation for how to set up the database locale: database collation is `en_US.utf8` but must be `C`', store/postgres/src/connection_pool.rs:976:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 01 13:52:01.525 CRIT Database does not use C locale. Please check the graph-node documentation for how to set up the database locale, error: database collation is `en_US.utf8` but must be `C`, pool: main, shard: primary, component: ConnectionPool
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', /graph-node/store/postgres/src/connection_pool.rs:484:10

any idea please? i need help

regards.

**Comment by azf20** [comment]
thanks - fixed in https://github.com/graphprotocol/example-subgraph/commit/55f6b96ab20bfeb870bd859e16002e9612884fea
