### ISSUE TITLE
404 Not Found when installing

### ISSUE THREAD

**Issue by tomtomcrypto** [graphprotocol/example-subgraph#69]
When navigating to the root folder and using `yarn `(as per documentation on [graph-node repo](https://github.com/graphprotocol/graph-node)), this is what I get:

```
yarn install v1.22.21
[1/4] Resolving packages...
[2/4] Fetching packages...
error Error: https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed "404 Not Found"
    at ResponseError.ExtendableBuiltin (/home/tom/.cache/node/corepack/yarn/1.22.21/lib/cli.js:696:66)
    at new ResponseError (/home/tom/.cache/node/corepack/yarn/1.22.21/lib/cli.js:802:124)
    at Request.<anonymous> (/home/tom/.cache/node/corepack/yarn/1.22.21/lib/cli.js:66218:16)
    at Request.emit (node:events:517:28)
    at module.exports.Request.onRequestResponse (/home/tom/.cache/node/corepack/yarn/1.22.21/lib/cli.js:141751:10)
    at ClientRequest.emit (node:events:517:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:517:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by shadmau** [comment]
See https://github.com/graphprotocol/example-subgraph/issues/64#issuecomment-1810829732
